[pytest]
testpaths = testcases
addopts =
    -q
    --strict-markers
    --html=reports/pytest_report.html
    --self-contained-html
    --reruns 1
    --reruns-delay 1
markers =
    smoke: quick smoke tests
    regression: regression tests
